export const sideProyects = [
  {
    id: "1",
    name: "Qr Component",
    image: "/proyectos/sideProyects/QrComponent.png",
    type: "FrontEnd Mentor Challenge",
    desc: "Challenge que hice para FrontEnd mentor que se basaba en crear un componente de QR con los elementos que te brindaban.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/FrontendMentor-QrComponent",
    deployUrl: "https://frontend-mentor-qr-component-pi.vercel.app/",
  },
  {
    id: "2",
    name: "Blog Preview Card",
    image: "/proyectos/sideProyects/BlogPreview.png",
    type: "FrontEnd Mentor Challenge",
    desc: "Challenge que hice para FrontEnd mentor que se basaba en crear una card que simulaba una preview de un post, hecho con elementos brindados por ellos.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/Blog-Preview-Card",
    deployUrl: "https://blog-preview-card-theta-sooty.vercel.app/",
  },
  {
    id: "3",
    name: "Social Links Card",
    image: "/proyectos/sideProyects/SocialLinks.png",
    type: "FrontEnd Mentor Challenge",
    desc: "Challenge de frontend mentor en donde debo hacer un componente que contenga varios links de mis redes sociales. Con elementos proporcionados por ellos.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/Social-Links-Card",
    deployUrl: "https://social-links-card-ten.vercel.app/",
  },
  {
    id: "4",
    name: "Recipe Page",
    image: "/proyectos/sideProyects/RecipePage.png",
    type: "FrontEnd Mentor Challenge",
    desc: "Un challenge de Front End mentor, sobre hacer una pagina con una receta para un platillo detallado. Hecho con elementos brindados por ellos.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/recipe-page",
    deployUrl: "https://recipe-page-ashy-rho.vercel.app/",
  },
];
