export const sideProjectsEn = [
  {
    id: "1",
    name: "Qr Component",
    image: "/proyectos/sideProyects/QrComponent.png",
    desc: "Challenge I completed for Frontend Mentor, which consisted of creating a QR component using the assets they provided.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/FrontendMentor-QrComponent",
    deployUrl: "https://frontend-mentor-qr-component-pi.vercel.app/",
  },
  {
    id: "2",
    name: "Blog Preview Card",
    image: "/proyectos/sideProyects/BlogPreview.png",
    desc: "Challenge from Frontend Mentor focused on building a card that simulates a blog post preview, using elements provided by them.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/Blog-Preview-Card",
    deployUrl: "https://blog-preview-card-theta-sooty.vercel.app/",
  },
  {
    id: "3",
    name: "Social Links Card",
    image: "/proyectos/sideProyects/SocialLinks.png",
    desc: "Frontend Mentor challenge where I had to create a component containing several links to my social networks, using the assets provided.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/Social-Links-Card",
    deployUrl: "https://social-links-card-ten.vercel.app/",
  },
  {
    id: "4",
    name: "Recipe Page",
    image: "/proyectos/sideProyects/RecipePage.png",
    desc: "A Frontend Mentor challenge about creating a detailed recipe page for a dish, using the elements provided by them.",
    techUsed: ["Next.js", "Tailwind CSS", "Vercel"],
    repoUrl: "https://github.com/Franki09/recipe-page",
    deployUrl: "https://recipe-page-ashy-rho.vercel.app/",
  },
];
